from userbot import bot as ULTRON
from userbot.utils import admin_cmd as choot

x = True
@ULTRON.on(choot(pattern="abuse"))
async def yashraid(event):
    while x != False:
       
        await event.delete()
        kek = event.chat_id
        await ULTRON.send_message(kek, "TERI MA KI CHOOXT MAARUU BSDKEE")
        await ULTRON.send_message(kek, "TERI BHN KA BHOSXDA FAAD DIA MADARCHOD")
        await ULTRON.send_message(kek, "TERI BHN KI GANXD ME DYNAMTE LAGA KE UDA DIA")
        await ULTRON.send_message(kek, "ULTRON OP HAI HM BAAP BOLTE HMKO")
        await ULTRON.send_message(kek, "TERI MAA KO CHOODUU")
        await ULTRON.send_message(kek, "MAADARCHODD")
        await ULTRON.send_message(kek, "😂")
        await ULTRON.send_message(kek, "ROJJ MERE")
        await ULTRON.send_message(kek, "LODEE PE")
        await ULTRON.send_message(kek, "AAKEE UCHALTII")
        await ULTRON.send_message(kek, "HAII")
        await ULTRON.send_message(kek, "TERI GANND TOD DI JAYEGI MADDRCHOOD")
        await ULTRON.send_message(kek, "😂")
        await ULTRON.send_message(kek, "TERI MAA KA BHOOSSDA FAADU DOGLE MADRCHODD")
        await ULTRON.send_message(kek, "BEHEN")
        await ULTRON.send_message(kek, "KII CHUTTT")
        await ULTRON.send_message(kek, "AUR GANND")
        await ULTRON.send_message(kek, "MAR MARKE")
        await ULTRON.send_message(kek, "EK KAR DIYAA")
        await ULTRON.send_message(kek, "ULTRON MEMBER IS ALWAYS ON FIRE")
        await ULTRON.send_message(kek, "😂")
        await ULTRON.send_message(kek, "MADERRRRCHODDO")
        await ULTRON.send_message(kek, "TUM SABB KAA")
        await ULTRON.send_message(kek, " BAAAP HAII")
        await ULTRON.send_message(kek, "ULTRON HAI HM HMKO KAHTE H OP AUR BETE TUM ULTRON KE LAND KI TOPI")
        await ULTRON.send_message(kek, "😂")
        await ULTRON.send_message(kek, "TERI GAMD TOD DI JAYEGI MADDRCHOD")
        await ULTRON.send_message(kek, "KII MAA")
        await ULTRON.send_message(kek, "KAA RAPEE")
        await ULTRON.send_message(kek, "KR DIYAA")
        await ULTRON.send_message(kek, "EKDUM GHODII")
        await ULTRON.send_message(kek, "BANAKEE")
        await ULTRON.send_message(kek, " CHODAA")
        await ULTRON.send_message(kek, "ULTRON NE CHOD DIA TUJE")
        await ULTRON.send_message(kek, "😂")
        await ULTRON.send_message(kek, "TUMHARII MAA KO")
        await ULTRON.send_message(kek, "AISAA")
        await ULTRON.send_message(kek, "CHODAA GHARR")
        await ULTRON.send_message(kek, "TAKK")
        await ULTRON.send_message(kek, "APNII CHUTT")
        await ULTRON.send_message(kek, "PAKADD")
        await ULTRON.send_message(kek, "KEE")
        await ULTRON.send_message(kek, "ROTII")
        await ULTRON.send_message(kek, "GAEE HAII")
        await ULTRON.send_message(kek, "AB BHII")
        await ULTRON.send_message(kek, "TIME HAI")
        await ULTRON.send_message(kek, "HUME BAAP")
        await ULTRON.send_message(kek, "BOLDOO")
        await ULTRON.send_message(kek, "😂")
        await ULTRON.send_message(kek, "AISE BHII")
        await ULTRON.send_message(kek, "TUMHARII MAA")
        await ULTRON.send_message(kek, "TO ROZZ HUMSEE")
        await ULTRON.send_message(kek, "CHUDTI HI HAII")
        await ULTRON.send_message(kek, "ROZZ KALAPTI HAII")
        await ULTRON.send_message(kek, "WO DEKHO")
        await ULTRON.send_message(kek, "TERA BAAP")
        await ULTRON.send_message(kek, "BETHA HAI")
        await ULTRON.send_message(kek, "GHODEE PEE")
        await ULTRON.send_message(kek, "TERI GANND TOD DI JAYEGI MADDRCHOD TUMHARA BAAP HU ME ULTRON WALE GANND FAAD KE RAKH DENGE TERI MADARCHOOD")
        await ULTRON.send_message(kek, "TUMHARII")
        await ULTRON.send_message(kek, "MAA")
        await ULTRON.send_message(kek, "MEREEE")
        await ULTRON.send_message(kek, "LODEEE")
        await ULTRON.send_message(kek, "OHH YEAHHH")
        await ULTRON.send_message(kek, "KYAA MASTT")
        await ULTRON.send_message(kek, "MAZAA DETI")
        await ULTRON.send_message(kek, "HAII")
        await ULTRON.send_message(kek, "TUMHARII MAA")
        await ULTRON.send_message(kek, "ULTRON NE TUMHARI BHN KO PURII RAT CHOXDAAA ")
        await ULTRON.send_message(kek, "😂")
        await ULTRON.send_message(kek, "TERI MAKI CHOOT 3 BAAR")
        await ULTRON.send_message(kek, "BAAP HAII H HUM")
        await ULTRON.send_message(kek, "TERII MAA")
        await ULTRON.send_message(kek, "KOO")
        await ULTRON.send_message(kek, "BHUTT GANDAA CHODAA")
        await ULTRON.send_message(kek, "BHOXDIKE AUKAAT BNA FRR ULTRON SE PANGE LENA")
        await ULTRON.send_message(kek, "GANDUUU")
        await ULTRON.send_message(kek, "KIII MAAA")
        await ULTRON.send_message(kek, "KIII CHUTTT")
        await ULTRON.send_message(kek, "LETE SAMAY")
        await ULTRON.send_message(kek, "USKII")
        await ULTRON.send_message(kek, "CHUTTT")
        await ULTRON.send_message(kek, "MEEE MAINEE")
        await ULTRON.send_message(kek, "GARAM LOHEE")
        await ULTRON.send_message(kek, "KAA SARIYAA")
        await ULTRON.send_message(kek, "DAAL DIYAA")
        await ULTRON.send_message(kek, "KALAP GYII")
        await ULTRON.send_message(kek, "TERI BHN KE GORE BOOBS AAHAAH AAH AAHA AAAHA AAHA AAAHH")
        await ULTRON.send_message(kek, "TERI MA KI CHOOXT FAD DI MENE BHOOSSDIKE ")
        await ULTRON.send_message(kek, "TERE BAAP")
        await ULTRON.send_message(kek, "RHEGE HUM")
        await ULTRON.send_message(kek, "HUMESAA")
        await ULTRON.send_message(kek, "ROZZ TMHARIII")
        await ULTRON.send_message(kek, "MAA KOO")
        await ULTRON.send_message(kek, "GHODII BANAKEE")
        await ULTRON.send_message(kek, "CHODEEEGEE")
        await ULTRON.send_message(kek, "TERI GAMD TOD DI JAYEGI MADDRCHOD KIII")
        await ULTRON.send_message(kek, "MAAAA")
        await ULTRON.send_message(kek, "CHUDD GYIII")
        await ULTRON.send_message(kek, "😂")
        await ULTRON.send_message(kek, "TERA ASLIII")
        await ULTRON.send_message(kek, "BAAAP")
        await ULTRON.send_message(kek, "MAIN HI HUINN YASH")
        await ULTRON.send_message(kek, "MERAA NAJAYAZ🤣")
        await ULTRON.send_message(kek, "BETA HAI TUU")
        await ULTRON.send_message(kek, "TERI MAA KI CHUUTTT AHHHH GZB BHSODDA BNA DIYAA")
        await ULTRON.send_message(kek, "HUMSE BAKCHODI NA KRRR TELE PR RHNE LAYAK NHI BACHEGA")
        await ULTRON.send_message(kek, "MAAADDRRCHHHOOODD")
        await ULTRON.send_message(kek, "LOOWDEE KEE BAAL")
        await ULTRON.send_message(kek, "LAAWDDDEEE KEE BAAL")
        await ULTRON.send_message(kek, "JHHAAATTT SEE SHAKAL KE")
        await ULTRON.send_message(kek, "CHINARRR MADRCHODDD")
        await ULTRON.send_message(kek, "RAMDI KI AULAAD")
        await ULTRON.send_message(kek, "TERRIII MAAA KO TERE SAMNE CHOODTA HU")
        await ULTRON.send_message(kek, "BSSDDKKEE BAAP SE PANGE LENGE")
        await ULTRON.send_message(kek, "YEEE LODDUUU KE BAAL")
        await ULTRON.send_message(kek, "JHHAAATTT BHAR KI AAUUKAAT NHI H")
        await ULTRON.send_message(kek, "AAYYYY HHHHH BAAAAPPP SSSEEE BHIIIDDHNEE MADARCHHHHOODDD")
        await ULTRON.send_message(kek, "BBHHOOSSDDDIIKEEEE APNIII MAA KO DWAI LAA KRRRR DEE")
        await ULTRON.send_message(kek, "MAADDRRRCCCHHHOOODDDD TERIIII MAA KIII CCCHHHUUUTTT SSSEEE KHUUNNN NIKALLLL DIYAA HH BBEETTIICCHHOODD")
        await ULTRON.send_message(kek, "CHAKKKAAA HHH TUUUU MAAADDRRCHHHOODDDD")
        await ULTRON.send_message(kek, "JJHHHAAATEEE JITNI")
        await ULTRON.send_message(kek, "BHIIIII BAAADDIII HOO")
        await ULTRON.send_message(kek, "RHHHTTAAAA LUNNNNNDD KEEE NICHEE HI HHHH")
        await ULTRON.send_message(kek, "BETICCCHHOOODD")
        await ULTRON.send_message(kek, "BHHHHOOOSSSDDIIIIKKEEEE TEEERRIIII AAUUKKAAAT MERA MUUUTT")
        await ULTRON.send_message(kek, "PIINEEE KI HHHH USSEEE PIII OR KKKHUUSSHHH")
        await ULTRON.send_message(kek, "RAHHHH BETIIICHHOOODDD CHIINARRR")
        await ULTRON.send_message(kek, "AAJJJ KEEE BAAD ULTRON SE PANGA")
        await ULTRON.send_message(kek, "MATTT LEENNAA MADRCHOODDD")
        await ULTRON.send_message(kek, "NHIII TTOO AGLA")
        await ULTRON.send_message(kek, "NUMBERRR TERE PURI KHANDANNN")
        await ULTRON.send_message(kek, "KIIII ORRTEEEE KAA HOGAAA")
        await ULTRON.send_message(kek, "CHINNARRRR BHOSDIKAAA")
        await ULTRON.send_message(kek, "ULTRON SE H BHNCCHOOODDDD")
        await ULTRON.send_message(kek, "YAHIII PATAKKK KR")
        await ULTRON.send_message(kek, "CHHHOOOODDDD DENGE")
        await ULTRON.send_message(kek, "TUMMM JESEE KITNOOO")
        await ULTRON.send_message(kek, "KOOO CHOOOOOOODDDDD KRRR CHOD DIYAA GANDUUU")
        await ULTRON.send_message(kek, "TELEGRAM ME RAHNA HAI TO ULTRON KO PAPA BOLNA PAREGA WARNA TUMHARII BHN XUDEGI AISE HI ROJ")
        
        
